Repository knative/homebrew-client, pull requests merged in 2020-06, with the labels that each got.

#4 Revert to 0.14
  kn.rb
  kn@0.14.rb
Labels: approved

#7 Add linux support.
  kn.rb
Labels: approved, cla: yes, lgtm, size/S

#8 Update to 0.15.2
  kn.rb
Labels: approved, cla: yes, size/XS
