Repository knative/homebrew-client, pull requests merged in 2022-10, with the labels that each got.

#80 Install arm builds via brew
  hack/update-versions.sh
  kn.rb
  kn@1.6.rb
Labels: approved, lgtm, size/M, kind/enhancement

#84 Update kn to v1.8.1
  kn.rb
Labels: approved, size/S, lgtm

#85 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#86 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
