Repository knative/homebrew-client, pull requests merged in 2022-04, with the labels that each got.

#46 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#48 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#47 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, size/XS, lgtm

#52 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
