Repository knative/homebrew-client, pull requests merged in 2022-07, with the labels that each got.

#65 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#63 Add script to update plugin versions
  hack/update-versions.sh
Labels: approved, lgtm, size/M

#67 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#68 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#69 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review
