Repository knative/homebrew-client, pull requests merged in 2024-03, with the labels that each got.

#137 Fix checksum in 1.6 file
  kn@1.6.rb
Labels: approved, size/XS, lgtm

#139 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#138 Add update script to fetch new kn version and update formulas
  .github/workflows/knative-homebrew-test.yaml
  .github/workflows/knative-update-release.yaml
  hack/update-taps.sh
  kn.rb
  kn@1.12.rb
Labels: approved, lgtm, size/L

#140 Update knative-update-release.yaml
  .github/workflows/knative-update-release.yaml
Labels: approved, size/XS, lgtm

#141 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#142 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
